### ISSUE TITLE
Add support for Set implementation

### ISSUE THREAD

**Issue by nohitme** [konmik/solid#1]
(this is more like a feature request)

I ran across this library and I would like to start using this. However the library supports only List and Map but not Set, which can be very useful for different use cases.

I wonder if it's possible for you to add Set implementation any time soon?

**Comment by konmik** [comment]
Hi, this is possible. This week for sure, probably even today.

**Comment by nohitme** [comment]
Thanks for the quick reply and the great news!

**Comment by konmik** [comment]
Just interesting. What is the use case for Immutable Set?

**Comment by nohitme** [comment]
I think in most of cases sets will be used to hold distinct data objects. Say you have a collection of items read from different sources and you don't want repeated ones, that's when Set can be useful. (as long as the type object implements equals() and hashCode() properly)

I know the fact that Android utilizes List and Map a lot more than Set, but it's still good to have.

**Comment by konmik** [comment]
OK. 

So, immutable set is something that can be substituted with `SolidList` easily.

You can't use Set's functionality that it does not allow duplicate values - they just can't be added.

But you can construct a `SolidList` which does not have duplicate values just by calling `.distinct().toSolidList()` on any stream.

**Comment by nohitme** [comment]
Yes calling `.distinct().toSolidList()` would provide the expected result collection (despite the fact you might still have to iterate over entire list and filter out repeated items)

I guess what I would like have to is the definition of the Set interface. From any API (method) signatures, developers would not know a given List would contain only distinct items, but they can safely assume that when the sources are Sets.

I don't really need to call `add()` on an immutable set since it's unmodifiable anyways. But at least I would be able to construct an immutable set by passing any collection and get a set of distinct items, which would be identical to guava's `ImmutableSet.of()`

**Comment by konmik** [comment]
Done! :)

**Comment by nohitme** [comment]
Ha. Thank you for the quick responses and implementation! :)
