### ISSUE TITLE
No zip function

### ISSUE THREAD

**Issue by artemohanjanyan** [konmik/solid#13]
I wonder why SolidList doesn't have some zip function like one in Haskell or RxJava. Here is possible implementation: [link](https://gist.github.com/artemohanjanyan/bf0e573e65203721e86a712b0813f1ed).

**Comment by artemohanjanyan** [comment]
See https://github.com/artemohanjanyan/solid/commit/238c358f77af9e990081776b67b2d4d739e8df67

**Comment by konmik** [comment]
Hi, it does not have it just because nobody requested it.

BTW, this is a nice idea! :)

**Comment by konmik** [comment]
If you want to make a pull request, this could be great! :)

just replace

```
Stream<? extends S> with
```

with

```
Iterable<? extends S> with
```

**Comment by artemohanjanyan** [comment]
Done #15 :)
