### ISSUE TITLE
Add api for creating SolidList of values

### ISSUE THREAD

**Issue by artem-zinnatullin** [konmik/solid#5]
Hello, @konmik! Yes we use `Solid` :smile_cat: 

At the moment to create `SolidList` of values you need to either use `new SolidList<>(asList(value1, value2))` or `Stream.of(value1, value2).collect(toSolidList()))`

But both variants require additional objects :(

Can we please have a way to create `SolidList` directly from varargs?

**Comment by konmik** [comment]
Wow, nice to hear :)

Sure, I'll add it, probably even today.

**Comment by artem-zinnatullin** [comment]
Great! What about method name? 

Since `SolidList` extends `Stream` we can't use `of()`

**Comment by konmik** [comment]
maybe just a constructor? or `create`?

**Comment by artem-zinnatullin** [comment]
Well, since `SolidList` already has a lot of constructors — constructor may fit current design better, but varargs `T` will create unambiguoty between constructors with other parameters.

Will be greate to replace all constructors with static methods with different names but it'll break current API…

**Comment by konmik** [comment]
I have an idea of creating `SolidMap` with `map(...)`, so if we need to create `SolidList` we may probably want to call just `list(...)`

**Comment by artem-zinnatullin** [comment]
That would be awesome!

What about class `Solid` with static factories for `SolidList`, `SolidSet` and `SolidMap`?

**Comment by konmik** [comment]
I don's see a need in a such class. Why whould it be helpful?

**Comment by artem-zinnatullin** [comment]
Single point to create `Solid` collections, like `Collections`

**Comment by konmik** [comment]
hm... copying everything is not always ok. It is good to have a reason. :)

**Comment by konmik** [comment]
https://github.com/konmik/solid/commit/404279d5ea4b089f08ab41127d4725ce93a0eb26

**Comment by artem-zinnatullin** [comment]
Nice! Thanks!
