### ISSUE TITLE
Please provide any/every methods for Stream

### ISSUE THREAD

**Issue by thevery** [konmik/solid#8]
e.g like in groovy:
 - http://docs.groovy-lang.org/latest/html/groovy-jdk/java/lang/Iterable.html#every(groovy.lang.Closure)
 - http://docs.groovy-lang.org/latest/html/groovy-jdk/java/lang/Iterable.html#any(groovy.lang.Closure)

**Comment by konmik** [comment]
how about

`stream.map(predicate).reduce((a, b) -> a && b)`

?

**Comment by konmik** [comment]
and for `any`:

`stream.map(predicate).reduce((a, b) -> a || b)`

**Comment by konmik** [comment]
we can in fact optimize any down to:

`stream.filter(predicate).first().isPresent()`

**Comment by thevery** [comment]
it is possible for sure but not as readable as `any`/`every`

**Comment by konmik** [comment]
These operators look like they belong to the library, I'll add them.

**Comment by konmik** [comment]
https://github.com/konmik/solid/commit/0d60248673624098f7929029be0dd976c4826f5d
